---
x-common-settings: &common-settings
  build:
    context: .
    dockerfile: Dockerfile
    args:
      NODE_ENV: ${NODE_ENV:-}
      HOST_UID: ${HOST_UID:-}
      HOST_GID: ${HOST_GID:-}
  volumes:
    - ./client:/opt/node_app/app/client
    - ./server:/opt/node_app/app/server
    - notused:/opt/node_app/app/node_modules

services:
  app:
    <<: *common-settings
    init: true  # Handle signals correctly
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - NODE_ENV

  test:
    <<: *common-settings
    command: npm run test
    environment:
      - NODE_ENV=test
    profiles:
      - test

  lint:
    <<: *common-settings
    command: npm run lint
    environment:
      - NODE_ENV=development
    profiles:
      - lint

volumes:
  notused:
