services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/opt/node_app/app
      - /opt/node_app/node_modules
    environment:
      - NODE_ENV
